# Execution Path Test

In [40]:
import pandas as pd
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import KFold

from tensorflow.keras import utils
from keras.utils import to_categorical
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import joblib
from pathlib import Path, PurePosixPath
from tensorflow.keras.callbacks import EarlyStopping
from pprint import pprint

In [14]:
    # read the data
    #current_path = Path(__file__).resolve().parent
    df = pd.read_pickle(PurePosixPath('RtpDump_1.pkl'))
    encoder_file = PurePosixPath("encoder.save")
    model_file = PurePosixPath("model.h5")

    X, one_hot_y, class_num = encode_key(df['log key'], 'encoder.save', 5)
    model = model_build(5, class_num)
    classifier = fit_eval(model, model_file ,30, X, one_hot_y)

[[17. 24. 36. 44. 16.]
 [24. 36. 44. 16. 31.]
 [36. 44. 16. 31. 30.]
 ...
 [20. 20. 20. 20. 20.]
 [20. 20. 20. 20. 20.]
 [20. 20. 20. 20. 20.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Epoch 1/50
6891/6891 - 5s - loss: 0.1583 - accuracy: 0.9819 - val_loss: 0.0130 - val_accuracy: 0.9995
Epoch 2/50
6891/6891 - 5s - loss: 0.0567 - accuracy: 0.9907 - val_loss: 0.0023 - val_accuracy: 0.9999
Epoch 3/50
6891/6891 - 5s - loss: 0.0497 - accuracy: 0.9909 - val_loss: 0.0204 - val_accuracy: 0.9994
Epoch 4/50
6891/6891 - 5s - loss: 0.0472 - accuracy: 0.9911 - val_loss: 0.0019 - val_accuracy: 0.9999
Epoch 5/50
6891/6891 - 5s - loss: 0.0447 - accuracy: 0.9914 - val_loss: 0.0026 - val_accuracy: 0.9999
Epoch 6/50
6891/6891 - 5s - loss: 0.0435 - accuracy: 0.9917 - val_loss: 0.0028 - val_accuracy: 0.9999
Epoch 7/50
6891/6891 - 5s - loss: 0.0426 - accuracy: 0.9914 - val_loss: 0.0044 - val_acc

In [15]:
model = model_build(5, class_num)

In [16]:
classifier = fit_eval(model, model_file ,30, X, one_hot_y)

In [17]:
    print('===========================')
    # pprint(rebuild_data(X[:100], normal_result))
    print('================================')
    # print(anomaly_match(classifier, X[:100], one_hot_y[:100], 2 ))
    seq_pre_dict = anomaly_match(classifier, X[:100], one_hot_y[:100], 0.1)
    trace_df = df.iloc[:100,]
    
    new_trace_df = trace_seq_path(trace_df, seq_pre_dict)
    
    print(new_trace_df)
    new_trace_df.to_csv(PurePosixPath('trace_df.csv'))
    # train_batch(classifier, X[:100], one_hot_y[:100])
    # train_batch(classifier, X[:100], one_hot_y[:100], 0.5, 20)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
7/7 [==============================] - 0s 712us/step
Instructions for updating:
Please use `model.predict()` instead.
7/7 [==============================] - 0s 713us/step
[(14, 0.29119253), (32, 0.16001934), (47, 0.14783965), (31, 0.13416559)]
[(30, 0.3669674), (25, 0.15219292)]
[(30, 0.22291204),
 (42, 0.14844754),
 (41, 0.13239536),
 (51, 0.11444213),
 (25, 0.11051576)]
[(25, 0.11206782)]
[(30, 0.20514344),
 (42, 0.17685567),
 (41, 0.14477387),
 (51, 0.10431748),
 (25, 0.10390316)]
[(30, 0.20582317),
 (42, 0.14969486),
 (25, 0.11945817),
 (41, 0.11932996),
 (51, 0.115571454)]
[(30, 0.28738368), (51, 0.15108079), (41, 0.12739275), (47, 0.10691818)]
[(30, 0.

That is a potential anomaly prediction: 35 from sequence [50. 41. 30.  3. 42.]
[30, 42, 51, 41, 32]
[30, 15, 47]
That is a potential anomaly prediction: 41 from sequence [30.  3. 42. 35. 30.]
[30, 51, 15, 3, 47]
[30, 41, 42]
That is a potential anomaly prediction: 51 from sequence [42. 35. 30. 41. 51.]
[30, 41, 51]
[30, 47, 41, 51]
[30, 47, 41, 51]
That is a potential anomaly prediction: 3 from sequence [41. 51. 51. 51. 30.]
[15, 30, 47]
[30, 47]
[30, 32, 51]
That is a potential anomaly prediction: 3 from sequence [51. 30.  3. 30. 30.]
[30, 32, 41, 47, 15]
[33]
[30, 51, 47, 21, 14]
[30, 29, 32, 41]
That is a potential anomaly prediction: 38 from sequence [30.  3. 30. 33. 30.]
[51, 32, 3, 47, 14, 30]
[30, 25, 32]
That is a potential anomaly prediction: 51 from sequence [30. 33. 30. 38. 30.]
[30, 41, 42]
[30, 41, 42, 51]
[30, 41, 47, 51]
[30, 41, 51, 42]
[30, 47]
That is a potential anomaly prediction: 42 from sequence [51. 41. 42. 30. 51.]
[30, 41, 42]
[30, 41, 51, 47]
[30, 47]
That is 

<ipython-input-11-0a0c965e9c4c>:187: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trace_df[key] = value
<ipython-input-11-0a0c965e9c4c>:187: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trace_df[key] = value


# Parameter Anomaly Model (MAIN)

please check code run parameter function below first!

In [39]:
    import regex as re
    # load paths
    current_path = r'C:\Users\ashoaib\Desktop\Logs Analysis\test'
    df = pd.read_pickle(PurePosixPath('logs_data.pkl'))
    model_file = PurePosixPath("para_model.h5")
    scaler_file =  current_path
    label_file =  current_path
    trace_df = pd.read_csv(PurePosixPath('trace_df.csv'))
    
    # load testing parameter value vector
    eventId = 16
    # with categorical data inside
    data = df[df['EventTemplate']=='The Trace Reader for <*> tracing was successfully initialized and is fully functional."']['ParameterList']
    #data = data.apply(lambda x: re.sub(r'[\[\]\']',r'',x))
    print(data)
    print(data.shape[0])
    print(data.shape[0])
    # feature engineering for parameter value matrix
    col_num = data.shape[0]
    
    new_data = []

    # feature engineering for every single column
    for col_ord in range(col_num):
        print([row[col_ord] for row in data])
        new_data.append([row[col_ord] for row in data])
        # replace the missing values
        new_data[col_ord] = miss_rep_col(new_data[col_ord])

        # create paths to save encoder model
        label_encoder_path = Path(label_file).joinpath(str(eventId), str(col_ord) + 'label.save')
        
        if not Path(label_encoder_path).parent.is_dir():
            Path(label_encoder_path).parent.mkdir(parents=True, exist_ok=True)
        
        # encode categorical labels
        if pd.Series(new_data[col_ord]).dtype == 'O':
            new_data[col_ord] = lab_enc(new_data[col_ord], label_encoder_path.as_posix())            
        
        # nomalize the column
        # new_data[col_ord] = 
        # stan_cols(new_data[col_ord], col_ord, eventId, scaler_file)
        
        # reshape 2D to 1D
        new_data[col_ord] = np.reshape(new_data[col_ord],new_data[col_ord].shape[0])
    
    # shift the row to column   
    new_data = np.array(new_data).T
    n_steps = 5
    X, y = split_data(new_data, n_steps)
    
    # reshape x to (samples, time steps, features)
    train_X = np.array(X).reshape(-1, n_steps, len(data[0]))
    # reshape y to (samples, features)
    train_y = np.array(y).reshape(-1, len(data[0]))
    model = model_build_train(train_X, train_y, model_file)
    # model = keras.models.load_model(model_file)
    mse_error = model_predict(model, train_X[:50], train_y[:50])
    
    print(mse_error)
    # confidence = 0.99
    # print(confidence_interval(confidence, mse_error))
    fp_int = 0.97 
    tp_int = 0.999
    attempts = 10
    threshold1, threshold3, seq_pre_dict = anomaly_match(mse_error, fp_int, tp_int, eventId)
    # visual_mses(eventId, mse_error, threshold1, threshold3, fp_int, tp_int)
    lab_encoder_file = PurePosixPath("encoder_new.save")
    trace_df = trace_seq_path(trace_df, seq_pre_dict, eventId, lab_encoder_file)
    trace_df.to_csv(PurePosixPath('trace_df_new.csv'),index=False)
    steps = 5
    train_batch(model, model_file, train_X[:50], train_y[:50], steps, tp_int, attempts)
   

12         ['synchronous']
13        ['asynchronous']
107692     ['synchronous']
107693    ['asynchronous']
215372     ['synchronous']
215373    ['asynchronous']
282566     ['synchronous']
282567    ['asynchronous']
Name: ParameterList, dtype: object
8
8
['[', '[', '[', '[', '[', '[', '[', '[']


<ipython-input-39-147ad93a76cf>:37: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  if pd.Series(new_data[col_ord]).dtype == 'O':


AttributeError: 'NoneType' object has no attribute 'shape'

## Parameter Anomaly Code

In [4]:
'''
    standardization -- same position in the vector
    hstack -- stack columns 

'''
from sklearn.preprocessing import StandardScaler,RobustScaler, MinMaxScaler, Normalizer
from pathlib import Path, PurePosixPath
import numpy as np
import pandas as pd
import joblib
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras import utils
from tensorflow.keras.layers import Dense, LSTM, GRU
from tensorflow.keras import Sequential
from tensorflow.keras.callbacks import EarlyStopping
from numpy import subtract, square
import scipy.stats as st
import matplotlib.pyplot as plt
import tensorflow.keras

def miss_rep_col(col):
    ''' fill the missing data in parameter vector

    : param col: the single column in vector
    : return: pandas series column without missing data
    '''
    # check whether is categorical dtype
    if pd.Series(col).dtype == 'O':
        # replace nan string to None
        return pd.Series(col).replace(np.nan, "None")
    else:
        # replace nan integer to 0
        return pd.Series(col).replace(np.nan, 0) 


def lab_enc(cate_col, label_encoder_file):
    ''' encode categorical column in parameter vector to numeric data
    
    : cate_col: the single series column in vector
    : label_encoder_file: the path to save label encoder
    : return: encoded series numeric column 
    '''
    
    if Path(label_encoder_file).is_file():
        label_encoder = joblib.load(label_encoder_file)
    else:
        laber_encoder = LabelEncoder()
        # key_log_arr = cate_list_com.values
        label_encoder = laber_encoder.fit(cate_col)
        # save the encoder for labelling
        joblib.dump(label_encoder, label_encoder_file)

    label_encode_cate = label_encoder.transform(cate_col)

    return label_encode_cate


def stan_cols(col, col_ord, eventId, scaler_file):
    ''' normalize the matrix based on every column in parameter vector

    : param data: the parameter value matrix
    : param eventId: the event number in clusters
    : param scaler_file: the path to save/load scaler 
    : param col_ord: the order of col in a vector
    : return: normalized matrix
    '''
    
    scaler_path = Path(scaler_file).joinpath(str(eventId), str(col_ord) + 'scaler.save')
    
    if scaler_path.is_file():
        scaler = joblib.load(scaler_path.as_posix())
    
    else:
        scaler = StandardScaler() 
        # scaler = RobustScaler()
        # scaler = Normalizer()
        # reshape to 2D from 1D
        col = np.array(col).reshape(-1,1)
        scaler = scaler.fit(col)
    
    # standardilize column
    sat_col = scaler.transform(col)
    
    return sat_col


def split_data(data, n_steps):
    '''

    : param data: the matrix for one event cluster
    '''
    if isinstance(data, np.ndarray):
        length = data.shape[0]
    else:
        length = len(data)
    
    X, y = [], []
    for i in range(length):
        # create the end of position
        end_ix = i + n_steps
        # check whether the index excesses the boundary
        if end_ix > data.shape[0] -1:
            break

        # get the input and output for model
        X_seq, Y_seq = data[i: end_ix], data[end_ix]
        
        # avoid arrays in a array
        X.append(X_seq.tolist())
        y.append(Y_seq.tolist())

    return X, y

def model_build_train(train_X, train_y, model_file):
    '''
        the step is default one
    '''
    earlystopping = EarlyStopping(monitor='loss', patience=10)

    model = Sequential()
    model.add(LSTM(8,activation='relu',input_shape = (train_X.shape[1], train_X.shape[2]), return_sequences=True))
    model.add(LSTM(8,activation='relu'))
    model.add(Dense(train_y.shape[1]))

    model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])
    # fit model with validation
    model.fit(train_X, train_y, epochs=500, batch_size=16, callbacks = [earlystopping], validation_split=0.3, verbose=2, shuffle=False)
    
    # saving weights
    model.save(model_file.as_posix())

    return model


def mean_square_error(y_true, y_pred):
    ''' modified mse to compute squared error for parameter model evaluation

    :param y_true: the test y --- array
    :param y_pred: the predict y --- array
    :return: the mean of errors, the errors list
    '''
    # define the minus between two values
    # return original value
    d_matrix = subtract(y_true, y_pred)
    mses = []
    print('The shape of minus matrix is: {}'.format(d_matrix.shape))
    # compute mse for every row
    for i in range(d_matrix.shape[0]):
        # initialize to 0 for every new row
        sum_minus = 0
        for j in range(d_matrix.shape[1]):
            sum_minus += d_matrix[i, j] * d_matrix[i, j]
        # compute the mse for every row
        mse = np.mean(sum_minus)
        mses.append(mse)
    return mses


def model_predict(model, test_x, test_y):
    ''' 

    '''
    pre_y = model.predict(test_x, verbose=1)

    return mean_square_error(test_y, pre_y)


def confidence_interval(confidence, mse):
    ''' function to compute the confidence interval boundaries

    :param confidence: the confidence value or threshold, like 98%
    :param mses_list: the errors list
    :return: the boundaries
    '''
    # define the interval tuple
    return st.t.interval(confidence, len(mse)-1, loc=np.mean(mse), scale=st.sem(mse))


def anomaly_match(mses_list, fp_int, tp_int, eventId):
    '''
    : param mses_list: the list of mean square errors
    : param file_number: the matrix order
    : return: two thresholds (for false positive, true positive),
             the indexes of anomaly logs and false positive logs
    '''
    # here we use the max value as the threshold
    CI_fp1 = confidence_interval(fp_int, mses_list)
    
    # it is for the false positive detection
    threshold1 = CI_fp1[1]
    
    CI_an = confidence_interval(tp_int, mses_list)
    # save the result from prediction, index is the order in event matrix
    seq_pre_dict = {'seq_para':[],'para_pred':[]}
    # it is for the anomaly detection
    threshold2 = CI_an[1]

    print('[+] Reporting based on thresholds to match anomaly for Parameter Vector Model!')
    
    for i in range(len(mses_list)):
        seq_pre_dict['seq_para'].append(i)
        # default add 0 as normal
        seq_pre_dict['para_pred'].append(0)
        # compare the true positive predictions
        if mses_list[i] > threshold2:
            print('The {}th log in event {} sequence is potentially anomaly'.format(i, eventId))
            seq_pre_dict['para_pred'][-1] = 1
        # compare the false positive predictions
        elif mses_list[i] > threshold1:
            print('The {}th log in event {} sequence is false positive'.format(i, eventId))
            seq_pre_dict['para_pred'][-1] = 2
        else:
            continue

    return threshold1, threshold2, seq_pre_dict


def visual_mses(eventId, mses, threshold1, threshold2, CI1, CI2):
    ''' visualize the mse

    '''
    # create the x axis labels
    x_list = []
    for i in range(len(mses)):
        x_list.append(i)
    if len(x_list) < 1:
        return
    else:
        plt.plot(x_list, mses)
        # add the threshold lines with percentage
        plt.axhline(y=threshold1, color='b', linestyle="-", label='CI={}'.format(CI1))
        plt.axhline(y=threshold2, color='r', linestyle="-", label='CI={}'.format(CI2))
        plt.ylabel("Errors Values")
        # match the first num
        plt.title('Event '+ str(eventId) + ' ' + 'Errors Distribution')
        plt.legend()
        plt.show(block=False)
        plt.pause(3)
        plt.close()


def trace_seq_path(trace_df, seq_pre_dict, eventId, lab_encoder_file):
    ''' generate dataframe to view the prediction

    : param trace_df: the dataframe with numeric log key, record_id inside        
    '''
    # check whether the para_pred column has existed or not
    if 'para_pred' not in trace_df:
        # default assign 0
        trace_df['para_pred'] = 0

    lab_encoder = joblib.load(lab_encoder_file.as_posix())
    # {eventId: log message}

    event_log_map = dict(zip(lab_encoder.transform(lab_encoder.classes_), lab_encoder.classes_))
    # extract the original log message indexes
    ori_log = event_log_map[eventId]
    eventId_indexes = trace_df[trace_df['log key'] == ori_log].index
    
    assert len(eventId_indexes) != len(seq_pre_dict['para_pred']), " Length Not Matched "
    
    for i, index in enumerate(eventId_indexes):
        # replace the order with index
        seq_pre_dict['seq_para'][i] = int(index)
    
    for ord_index, df_index in enumerate(seq_pre_dict['seq_para']):
        trace_df['para_pred'][df_index] = seq_pre_dict['para_pred'][ord_index]

    return trace_df


def train_batch(para_model, model_file, batch_x, batch_y, steps, desired_thres, attempts):
    ''' update model with false positve and corrected wrong prediction
        stop train when predicted mes is smaller than a threshold or attempts reach a given num

    : param para_model: the original trained model
    : param batch_x: the x used to update the model
    : param batch_y: the normal prediction
    : param desired_thres: the threshold of confidence interval to match normal prediction
    : param attempts: the threshold to stop the training
    
    : return: updated model with adjusted weights
    '''
    # train with batch data first
    para_model.train_on_batch(batch_x, batch_y)
    # check the predict result
    mse_error = model_predict(para_model, batch_x, batch_y)
    # calculate the value matched the desired threshold for CI
    CI_AN = confidence_interval(desired_thres, mse_error)
    # compare every mse with the CI_AN
    for i in range(len(mse_error)):
        # set the exit condition
        success_flag = False
        no_of_attempts = 0
        # retrain if the mse is not acceptable
        while mse_error[i] > CI_AN[1] and (no_of_attempts < attempts):
            # convert 2D to 3D (samples, time steps, features)
            batch_x_one = np.reshape(batch_x[i], (1,batch_x[i].shape[0], batch_x[i].shape[1]))
            # convert 1D to 2D
            batch_y_one = np.reshape(batch_y[i], (1, len(batch_y[i])))
            para_model.fit(batch_x_one, batch_y_one)
            
            no_of_attempts += 1
            mse_one = model_predict(para_model, batch_x_one, batch_y_one)
            print("Attempt Number %d, Calculated error for this iteration %f" %(no_of_attempts, mse_one[0]))

            if mse_one < CI_AN[1]:
                success_flag = True
                break

        if (success_flag == False) and (no_of_attempts >= attempts):
            print("[-] Failed to incorporate this feedback")

        if success_flag == True:
            print("[+] Feedback incorporated \n")
            print("Took %d iterations to learn!" %(no_of_attempts))

    # saving weights
    para_model.save(model_file.as_posix())

    return para_model


## Execution Path Code

In [37]:

def miss_rep_col(column_list):
    #if column_list.dtype.name != 'category':
        # replace nan string to None
    #    return column_list.replace(np.nan, "None")
    #else:
        # replace nan integer to 0
    #return column_list.replace(np.nan, 0) 
    pass

def lab_enc(cate_list, label_encoder_file):
    # feature engineering for list
    cate_list_com = miss_rep_col(cate_list)
    
    if Path(label_encoder_file).is_file():
        label_encoder = joblib.load(label_encoder_file)
    else:
        laber_encoder = LabelEncoder()
        # key_log_arr = cate_list_com.values
        label_encoder = laber_encoder.fit(cate_list_com)
        # save the encoder for labelling
        joblib.dump(label_encoder, label_encoder_file.as_posix())
    
    label_encode_cate = label_encoder.transform(cate_list_com)

    return label_encode_cate


def encode_key(key_log_series, label_encoder_file, n_steps):
    ''' encode the string log key and one hot encode the number then

    '''
    label_encode_cate = lab_enc(key_log_series, label_encoder_file)
    # load label_encoder to return number of classes
    label_encoder = joblib.load(label_encoder_file)
    class_num = len(label_encoder.classes_)
    
    X, y = split_data(label_encode_cate, n_steps)

    # one hot encoding the labelled numeric log key array
    one_hot_y = utils.to_categorical(y) # np_utils

    X = np.array(X).astype(float)
    
    return X , one_hot_y, class_num


def model_build(steps, class_num):
    ''' build the model with two hidden layers
    
    : return: compiled model
    '''
    model = Sequential()
    # input dim is the length of steps/history
    model.add(Dense(16, input_dim=steps, activation='relu'))
    model.add(Dense(16, activation='relu'))
    # output unit is the number of classes
    model.add(Dense(class_num,activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

    return model


def split_data(key_log_list, n_steps):
    X, y = [], []
    for i in range(len(key_log_list)):
        # create the end of position
        end_ix = i + n_steps
        # check whether the index excesses the boundary
        if end_ix > len(key_log_list) -1:
            break

        # get the input and output for model
        X_seq, Y_seq = key_log_list[i: end_ix], key_log_list[end_ix]
        # avoid arrays in a array
        X.append(X_seq.tolist())
        y.append(Y_seq.tolist())

    return X, y


def fit_eval(model, model_file, random_seed, X, y):
    
    if Path(model_file).is_file():
        model = load_model(model_file.as_posix())# fit the model
    else:
        print(X)
        earlystopping = EarlyStopping(monitor='accuracy', patience=10)
        

        # classifier = KerasClassifier(model, epochs=200, batch_size =5,  verbose=0)
        # evaluate the model
        # kfold = KFold(n_splits=10, shuffle=True, random_state=random_seed)
        print('=================')
        print(y)
        # results = cross_val_score(classifier, X, y, cv=kfold)
        # print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

        # in order to save model --- use fit
        model.fit(X, y, epochs=50, batch_size =5, validation_split =0.2, callbacks = [earlystopping], verbose=2)
    
        # saving weights
        model.save(model_file.as_posix())

    return model


def predict_sort(classifier, test_x, top_num):
    '''
    : param top_num: the top possibility to set as normal
    '''
    normal_result = []
    results = classifier.predict_proba(test_x, batch_size=16, verbose=1)
    # sort the result with shape of test_x.shape
    ## iterate the rows
    for row in range(results.shape[0]):
        # sort descending
        sorted_poss = [i for i in sorted(enumerate(results[row]), key=lambda x:x[1], reverse=True)]
        # extract the top num of possibilities tuple as the normal (class_num, possibility)
        normal_result.append(sorted_poss[: top_num])
    
    return normal_result


def rebuild_data(test_x, normal_result):
    ''' build normal sequences for updating 

    : param normal_result: checked predicted normal y -- list type with poss tuples inside
    '''
    assert test_x.shape[0] != len(normal_result), "Array Shape does not Match"
    # build normal sequence --- kind of N-gram
    normal_sequence = []
    
    for i in range(test_x.shape[0]):
        test_seq = test_x[i].tolist()
        normal_sequence.extend([ test_seq + [float(pro_y[0])]  for pro_y in normal_result[i]])

    return normal_sequence

    pprint(normal_sequence)


def anomaly_match(classifier, test_x, test_y, threshold):
    ''' match the top normal predict, anomaly logs if not matchable
    

    '''
    # pre_y is a list of predicted class number
    pre_y = classifier.predict_classes(test_x, batch_size=16, verbose=1)
    # save the possible prediction
    normal_result = []
    # save the seq and the prediction
    seq_pre_dict = {'seq_path':[], 'path_pred':[]}
    results = classifier.predict_proba(test_x, batch_size=16, verbose=1)
    # sort the result with shape of test_x.shape
    ## iterate the rows
    for row in range(results.shape[0]):
        # sort descending
        sorted_poss = [i for i in sorted(enumerate(results[row]), key=lambda x:x[1], reverse=True)]
        # pprint(sorted_poss)
        # print(sorted_poss)
        # extract the top num of possibilities tuple as the normal (class_num, possibility)
        pprint([clus_prob for clus_prob in sorted_poss if clus_prob[1] >= threshold])
        normal_result.append([clus_prob for clus_prob in sorted_poss if clus_prob[1] >= threshold])

    for i in range(len(pre_y)):
        # default add 0 as the prediction result to result column
        seq_pre_dict['seq_path'].append(list(test_x[i]) + [np.argmax(test_y[i])])
        # 0 is the normal
        seq_pre_dict['path_pred'].append(0)
        # print(np.argmax(test_y[i]))
        pprint([pre_y[0] for pre_y in normal_result[i]])
        if np.argmax(test_y[i]) not in [pre_y[0] for pre_y in normal_result[i]]:
            # change the prediction to anomaly with label 1
            seq_pre_dict['path_pred'][-1] = 1
            print("That is a potential anomaly prediction: {} from sequence {}".format(np.argmax(test_y[i]), test_x[i]))

    return seq_pre_dict    


def trace_seq_path(trace_df, seq_pre_dict):
    ''' generate dataframe to view the prediction

    : param trace_df: the dataframe with numeric log key, record_id inside        
    '''
    for key, value in seq_pre_dict.items():
        assert len(trace_df) == len(value)
        trace_df[key] = value

    return trace_df


def train_batch(exec_model, model_file, batch_x, batch_y, desired_proba, attempts):
    ''' update model with false positve and corrected wrong prediction
        stop train when predicted proba larger than a given value or attempts reach a given value

    : param exec_model: the original trained model
    : param batch_x: the x used to update the model
    : param batch_y: the normal or corrected y to update the prediction
    : param desired_proba: the threshold to stop the train_on_batch
    : param attempts: the threshold to stop the training
    
    : return: updated model with adjusted weights
    '''
    # train with batch data first
    exec_model.train_on_batch(batch_x, batch_y)
    # check the predict result
    pred_y = exec_model.predict_proba(batch_x, verbose=2)
    
    for i in range(len(batch_y)):
        # extract the predict proba for batch_y
        pre_proba = pred_y[i][int(np.argmax(batch_y[i]))]
        # set the exit condition
        success_flag = False
        no_of_attempts = 0
        # retrain on the single input and output
        while pre_proba <= desired_proba and (no_of_attempts<attempts):
            print(pre_proba)            
            exec_model.fit(np.reshape(batch_x[i],(1,-1)), np.reshape(batch_y[i],(1,-1)))
            
            no_of_attempts += 1

            pred_one_y = exec_model.predict_proba(np.reshape(batch_x[i],(1,-1)), verbose=2)
            pre_proba = pred_one_y[0][int(np.argmax(batch_y[i]))]
            
            print("Attempt Number %d, Predicted Proba for this iteration %f" %(no_of_attempts, pre_proba))

            if pre_proba > desired_proba:
                success_flag = True
                break

        if (success_flag == False) and (no_of_attempts >= attempts):
            print("[-] Failed to incorporate this feedback")

        if success_flag == True:
            print("[+] Feedback incorporated \n")
            print("Took %d iterations to learn!" %(no_of_attempts))

    # saving weights
    exec_model.save(model_file.as_posix())

    return exec_model